
name: Build
on: [push]
jobs:
  build_and_push:
    steps:
        - name: docker build
          run: docker buildx build --platform linux/amd64 -t vladimirbodrin/work_test:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
        - name: docker login
          run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        - name: docker push
          run: docker push vladimirbodrin/work_test:$GITHUB_REF_NAME-$GITHUB_RUN_ID